version: '3.8'

services:
  # База данных
  db:
    image: postgres:14
    container_name: shortener-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./internal/client/db/migrations:/docker-entrypoint-initdb.d
    networks:
      - shortener_network

  # Сервис на Go
  shortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shortener
    depends_on:
      - db
    ports:
      - "8082:8082"
    environment:
      DB_DSN: "host=db user=user password=password dbname=shortener sslmode=disable"
    volumes:
      - ./config.yaml:/app/config.yaml
    networks:
      - shortener_network

  # Swagger UI через Nginx
  swagger_ui:
    image: nginx:latest
    container_name: swagger-ui
    ports:
      - "8081:8081"
    volumes:
      - ./docs:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - shortener
    networks:
      - shortener_network

volumes:
  pg_data:

networks:
  shortener_network: